version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running tests"
      - go get -u github.com/synoa/helloworld
      - go test
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build hello.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello